import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { PlansProvider } from "@/features/plans/context/PlansContext";
import { AppProvider } from "@/providers/AppProvider";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AppProvider>
          <PlansProvider>
            {children}
          </PlansProvider>
        </AppProvider>
      </body>
    </html>
  );
}